package my.vaadin.bugrap;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ReportProperties extends VerticalLayout {
	protected Panel openBtnContainer;
	protected Button openInNewWnd;
	protected Label reportName;
	protected NativeSelect<org.vaadin.bugrap.domain.entities.Report.Priority> prioritySelector;
	protected NativeSelect<org.vaadin.bugrap.domain.entities.Report.Type> typeSelector;
	protected NativeSelect<org.vaadin.bugrap.domain.entities.Report.Status> statusSelector;
	protected NativeSelect<org.vaadin.bugrap.domain.entities.Reporter> assignedToSelector;
	protected NativeSelect<org.vaadin.bugrap.domain.entities.ProjectVersion> versionSelector;
	protected Button updateBtn;
	protected Button revertBtn;

	public ReportProperties() {
		Design.read(this);
	}
}
