package my.vaadin.bugrap;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ReportsOverview extends VerticalLayout {
	protected HorizontalLayout headerContainer;
	protected HorizontalLayout versionsContainer;
	protected NativeSelect<java.lang.String> versionSelector;
	protected HorizontalLayout filtersContainer;

	public ReportsOverview() {
		Design.read(this);
	}
}
